#!/bin/bash
rm -r dist
rm -r dte.egg-info
new_version=`grep version setup.py | \
    sed -r "s/.*version='([^']*)'.*/\1/g" | \
    awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}'`
sed -i "s/\(.*version='\).*',/\1$new_version',/g" setup.py
python3 ./setup.py sdist && \
    python3 -m twine upload dist/*
